### ISSUE TITLE
.on issue

### ISSUE THREAD

**Issue by xtreameprogram** [rannmann/node-steam-user-trade-tutorial#4]
Everytime I run the script, I get an error as seen below

client.friends.on('relationships', function(){
              ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/ford/main.js:142:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3

**Comment by tomasmartins** [comment]
I had the same problem, when i added the settings information and reinstalled all dependencies it started to work im not sure what fixed it

**Comment by Yoda3D** [comment]
I'm getting the same issue, if anyone figures out a fix, I would be very grateful.

**Comment by ghost** [comment]
Any update on this issue?
